import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Anek_Telugu } from "next/font/google";
import { cn } from "@/lib/utils";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const AnekTelugu = Anek_Telugu({ subsets: ["latin"],
  variable:"--font-caption"
 });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
         className={cn(
          geistSans.variable,
          geistMono.variable,
          AnekTelugu.variable,
         "flex flex-col font-sans min-h-screen "
       )}
       
      >
        {children}
      </body>
    </html>
  );
}
