import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Anek_Telugu } from "next/font/google";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/Theme/ThemeProvider";
import { SiteHeader } from "@/components/SiteHeader";
import { Providers } from "./providers";
import { Spacing } from "@/components/Spacing";
import { Footer } from "@/components/Footer";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const AnekTelugu = Anek_Telugu({
  subsets: ["latin"],
  variable: "--font-caption",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: {
    locale: string;
  };
}>) {
  return (
    <html lang="en" className=" flex min-h-screen">
      <body
        className={cn(
          geistSans.variable,
          geistMono.variable,
          AnekTelugu.variable,
          "min-h-screen w-full h-full bg-background font-sans text-foreground "
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <Providers locale={params.locale}>
            <div className=" flex min-h-screen bg-background flex-col">
              <SiteHeader />
              <Spacing size="md" />
              <main className="flex-1">{children}</main>
              <Spacing size="md" />
              <Footer />
            </div>
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
